#!/usr/bin/env php
<?php
/**
 * Craft console bootstrap file
 */

// Define path constants
const CRAFT_BASE_PATH = __DIR__;
const CRAFT_VENDOR_PATH = CRAFT_BASE_PATH . '/vendor';

// Load Composer's autoloader
require_once CRAFT_VENDOR_PATH . '/autoload.php';

if (class_exists(\Symfony\Component\VarDumper\VarDumper::class)) {
    require __DIR__ . '/config/dumper.php';
}

// Load and run Craft
/** @var craft\console\Application $app */
$app = require CRAFT_VENDOR_PATH . '/craftcms/cms/bootstrap/console.php';
$exitCode = $app->run();
exit($exitCode);
