baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Craft Slim Bridge'
primary: true
siteGroup: a39020df-8ab1-4178-89f1-b8b345546554 # Craft Slim Bridge
sortOrder: 1
